import type { SchedulerContext } from "./types";

export const demoSchedulerContext: SchedulerContext = {
  days: [
    { dayIndex: 1, label: "Lundi", isEnabled: true },
    { dayIndex: 2, label: "Mardi", isEnabled: true },
    { dayIndex: 3, label: "Mercredi", isEnabled: true, closedHalfDays: ["afternoon"] },
    { dayIndex: 4, label: "Jeudi", isEnabled: true },
    { dayIndex: 5, label: "Vendredi", isEnabled: true },
  ],

  periods: [
    {
      periodIndex: 1,
      label: "M1",
      startTime: "07:30",
      endTime: "08:25",
      halfDay: "morning",
      isTeachingPeriod: true,
      isBreakAfter: false,
    },
    {
      periodIndex: 2,
      label: "M2",
      startTime: "08:25",
      endTime: "09:20",
      halfDay: "morning",
      isTeachingPeriod: true,
      isBreakAfter: true,
    },
    {
      periodIndex: 3,
      label: "M3",
      startTime: "09:35",
      endTime: "10:30",
      halfDay: "morning",
      isTeachingPeriod: true,
      isBreakAfter: false,
    },
    {
      periodIndex: 4,
      label: "M4",
      startTime: "10:30",
      endTime: "11:25",
      halfDay: "morning",
      isTeachingPeriod: true,
      isBreakAfter: false,
    },
    {
      periodIndex: 5,
      label: "S1",
      startTime: "13:30",
      endTime: "14:25",
      halfDay: "afternoon",
      isTeachingPeriod: true,
      isBreakAfter: false,
    },
    {
      periodIndex: 6,
      label: "S2",
      startTime: "14:25",
      endTime: "15:20",
      halfDay: "afternoon",
      isTeachingPeriod: true,
      isBreakAfter: true,
    },
    {
      periodIndex: 7,
      label: "S3",
      startTime: "15:35",
      endTime: "16:30",
      halfDay: "afternoon",
      isTeachingPeriod: true,
      isBreakAfter: false,
    },
    {
      periodIndex: 8,
      label: "S4",
      startTime: "16:30",
      endTime: "17:25",
      halfDay: "afternoon",
      isTeachingPeriod: true,
      isBreakAfter: false,
    },
  ],

  classes: [
    {
      id: "classe_6e_a",
      name: "6e A",
      shortName: "6e A",
      levelCode: "6e",
      displayOrder: 1,
    },
    {
      id: "classe_6e_b",
      name: "6e B",
      shortName: "6e B",
      levelCode: "6e",
      displayOrder: 2,
    },
    {
      id: "classe_5e_a",
      name: "5e A",
      shortName: "5e A",
      levelCode: "5e",
      displayOrder: 3,
    },
  ],

  rooms: [
    { id: "salle_a", name: "Salle A", roomType: "ordinary" },
    { id: "salle_b", name: "Salle B", roomType: "ordinary" },
    { id: "salle_c", name: "Salle C", roomType: "ordinary" },
    { id: "labo_pc", name: "Labo P.C", roomType: "pc_lab" },
    { id: "labo_svt", name: "Labo SVT", roomType: "svt_lab" },
    { id: "terrain", name: "Terrain EPS", roomType: "sports_field" },
  ],

  teachers: [
    { id: "prof_maths", fullName: "M. Koné", shortName: "Koné" },
    { id: "prof_maths_2", fullName: "M. Kouamé", shortName: "Kouamé" },

    { id: "prof_pc", fullName: "M. N’Dri", shortName: "N’Dri" },
    { id: "prof_svt", fullName: "Mme Koffi", shortName: "Koffi" },

    { id: "prof_fr", fullName: "Mme Traoré", shortName: "Traoré" },
    { id: "prof_fr_2", fullName: "M. Diabaté", shortName: "Diabaté" },

    { id: "prof_hg", fullName: "M. Bamba", shortName: "Bamba" },
    { id: "prof_ang", fullName: "M. Soro", shortName: "Soro" },
    { id: "prof_eps", fullName: "Mme Yao", shortName: "Yao" },
    { id: "prof_edhc", fullName: "Mme Aka", shortName: "Aka" },
    { id: "prof_ap", fullName: "M. Guei", shortName: "Guei" },
    { id: "prof_musique", fullName: "Mme Boni", shortName: "Boni" },
  ],

  subjects: [
    {
      id: "maths",
      code: "MATHS",
      name: "Mathématiques",
      shortName: "Maths",
      isHeavy: true,
    },
    {
      id: "pc",
      code: "PC",
      name: "Physique-Chimie",
      shortName: "P.C",
      isHeavy: true,
      defaultRoomType: "pc_lab",
    },
    {
      id: "svt",
      code: "SVT",
      name: "Sciences de la Vie et de la Terre",
      shortName: "SVT",
      isHeavy: true,
      defaultRoomType: "svt_lab",
    },
    {
      id: "francais",
      code: "FR",
      name: "Français",
      shortName: "Français",
      isHeavy: true,
    },
    {
      id: "hg",
      code: "HG",
      name: "Histoire-Géographie",
      shortName: "H-G",
      isHeavy: true,
    },
    {
      id: "anglais",
      code: "ANG",
      name: "Anglais",
      shortName: "Anglais",
      isHeavy: false,
    },
    {
      id: "eps",
      code: "EPS",
      name: "EPS",
      shortName: "EPS",
      isHeavy: false,
      defaultRoomType: "sports_field",
    },
    {
      id: "edhc",
      code: "EDHC",
      name: "EDHC",
      shortName: "EDHC",
      isHeavy: false,
    },
    {
      id: "ap",
      code: "ARTS",
      name: "Arts plastiques",
      shortName: "Arts plastiques",
      isHeavy: false,
    },
    {
      id: "musique",
      code: "MUS",
      name: "Éducation musicale",
      shortName: "Musique",
      isHeavy: false,
    },
  ],

  roomPreferences: [
    {
      classId: "classe_6e_a",
      roomId: "salle_a",
      priority: 1,
      usageType: "main",
      isAllowed: true,
    },
    {
      classId: "classe_6e_b",
      roomId: "salle_a",
      priority: 1,
      usageType: "main",
      isAllowed: true,
    },
    {
      classId: "classe_5e_a",
      roomId: "salle_b",
      priority: 1,
      usageType: "main",
      isAllowed: true,
    },
    {
      classId: "classe_6e_a",
      roomId: "salle_c",
      priority: 2,
      usageType: "alternative",
      isAllowed: true,
    },
    {
      classId: "classe_6e_b",
      roomId: "salle_c",
      priority: 2,
      usageType: "alternative",
      isAllowed: true,
    },
    {
      classId: "classe_5e_a",
      roomId: "salle_c",
      priority: 2,
      usageType: "alternative",
      isAllowed: true,
    },
  ],

  terrainRules: {
    avoidBreakInsideMultiPeriodBlock: true,
    enablePcSvtTandem: false,
    pcSvtTandemScope: "disabled",
    pcSvtTandemMode: "parallel",
    pcSvtTandemClassIds: [],
    allowPcInOrdinaryRoomWhenNoLab: true,
    allowSvtInOrdinaryRoomWhenNoLab: true,
    allowEpsInOrdinaryRoomWhenNoField: true,
    allowComputerInOrdinaryRoomWhenNoLab: true,
    treatSportsFieldAsSharedResource: true,
    epsMaxSimultaneousCoursesPerField: 2,
    epsHotHourMode: "soft",
    avoidStudentGaps: true,
    avoidTeacherGaps: true,
    avoidSingleHourReturn: true,
    avoidHeavySubjectsBackToBack: true,
    avoidSameSubjectSameDay: true,
    balanceHalfDays: true,
    preferMainClassRoom: true,
  },

  teacherUnavailability: [
    {
      teacherId: "prof_maths",
      dayIndex: 2,
      halfDay: "morning",
      constraintType: "strict",
      reason: "Indisponible mardi matin",
    },
    {
      teacherId: "prof_eps",
      dayIndex: 5,
      halfDay: "afternoon",
      constraintType: "strict",
      reason: "Indisponible vendredi après-midi",
    },
  ],

  serviceAssignments: [],
};